name: Status Check
run-name: Status Check on push
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on Failure
        if: failure()
        run: echo "Running the failure step"
      - name: Runs on Success
        # this is default behaviour
        if: success()
        run: echo 'Runs on Success'
      - name: Runs always
        if: always()
        run: echo 'Run this step always'
      - name: Run on cancelled
        if: cancelled()
        run: echo 'Run this step when cancelled'
  jbb-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'job 2'
