name: Show Working Directory
on: [push]

defaults:
  run:
    shell: bash

jobs:
  display-working-dir-info-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-working-dir-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory
        run: |
          Get-Location
          pwd
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE